### ISSUE TITLE
Clarify threading model of libsimpleservo callbacks and implemented task queue

### ISSUE THREAD

**Issue by philip-lamb** [MozillaReality/servo-unity#1]
Unity API can be invoked only on main thread, so any callbacks on non-main threads that should invoke Unity API will need to be handed off to a task queue on main thread.

**Comment by paulrouget** [comment]
That's a situation we have with other platforms.
What type of callbacks are problematic?

**Comment by philip-lamb** [comment]
Fixed in c78956bfc063a42c156262b56259aff8d387951c
