### ISSUE TITLE
Is it currently possible to build for win10 / android?

### ISSUE THREAD

**Issue by TheBricktop** [MozillaReality/servo-unity#11]
Id like to know is there a possibility to build servo on win10 or android on for example docker.

**Comment by philip-lamb** [comment]
This project is no longer being supported by Mozilla. You can follow progress on other platforms at https://github.com/philip-lamb/servo-unity/.

**Comment by TheBricktop** [comment]
@philip-lamb  but i cant ask questions there :( there is no discussion page or issues tab.

**Comment by philip-lamb** [comment]
@TheBricktop  I've added an issues page. File away.
