### ISSUE TITLE
Oculus Quest 2 support

### ISSUE THREAD

**Issue by HerrAugust** [MozillaReality/servo-unity#12]
Hi,

I need to use this embedded browser in a project for Oculus Quest 2 on Unity 2020. Is it possible? I just need a really simple website with javascript working.

Thanks!

**Comment by philip-lamb** [comment]
Mozilla is no longer supporting this project. I've continued some development at https://github.com/philip-lamb/servo-unity/ for the plugin https://github.com/philip-lamb/servo/ for the libsimpleservo2 build, however Android support is not included. The main issue is that Servo does not have a tested build on Android. If a user were to set it up I'd certainly merge it.
