### ISSUE TITLE
Release or building on Linux

### ISSUE THREAD

**Issue by HerrAugust** [MozillaReality/servo-unity#13]
Hi,

Is it possible to build this project on Ubuntu? Unfortunately I do not have a laptop with macOS and as I read on the README it is needed.

If not possible to build it on Ubuntu, can anyone share a built version of this plugin for Unity?

Thanks!

**Comment by philip-lamb** [comment]
In theory it could be built for Linux, but there are no project files for it at the moment. If you create some, feel free to contribute at https://github.com/philip-lamb/servo-unity.

**Comment by itsmeneoagain** [comment]
can explain how can we achieve it , i will provide a PR for the same after doing it and plus how can we build it for Oculus quest 2
