### ISSUE TITLE
Archive this project

### ISSUE THREAD

**Issue by TheNotary** [MozillaReality/servo-unity#16]
It looks like this project ended before it reached a usable state.  As such it would be generous to indicate this at the top of the readme with and archive the repo.

**Comment by philip-lamb** [comment]
Mozilla removed my ability to do anything with the repo (including archiving it or whatever) when it ended Mozilla Research. The project was in a usable state at the time  for mac OS, but has continued since here; https://github.com/philip-lamb/servo-unity
