### ISSUE TITLE
Roadmap for other platforms?

### ISSUE THREAD

**Issue by dakom** [MozillaReality/servo-unity#2]
Wondering if there's a roadmap planned out for other platforms.

Personally I'm most interested Android/Oculus (for VR) and, ironically, WebGL/Wasm

**Comment by philip-lamb** [comment]
The other desktop platforms are likely to be first, but Android is definitely possible. WebGL+WASM... yeah, not so much. I mean, we can all conceive of how that _could_ work, but we're a long way off Servo running in wasm yet.

**Comment by AlterHowdegen** [comment]
Is there any chance to support iOS? Or completely prohibited by Xcode? Would it be technically possible, but rejected in the official AppStore (thus still usable via alternative enterprise distribution)?

**Comment by jdm** [comment]
The apple app store license prohibits submitting anything based on Servo, so that platform is not a priority at this time.

**Comment by AlterHowdegen** [comment]
Yeah, fair enough. So it would be technically possible for iOS (without AppStore though), but of course that's a much rarer case, so makes sense not to focus on that. Unfortunately makes it pointless for users relying on iOS.

**Comment by blasco** [comment]
This is amazing. Any updates on when this will be available for the Oculus Quest?

**Comment by mura94** [comment]
Also curious if Android & Quest support is on the roadmap still?

**Comment by philip-lamb** [comment]
This project is no longer supported by Mozilla. You can find its continuation at https://github.com/philip-lamb/servo-unity.
