### ISSUE TITLE
Running javascript

### ISSUE THREAD

**Issue by bc** [MozillaReality/servo-unity#4]
Awesome implementation! Is there a good way to send arbitrary javascript (or receive) on a given website so I can affect the DOM & manipulate the site from the `C#` side? If not, what strategies could I take to achieve this? Thanks!

**Comment by jdm** [comment]
It might be possible to start the engine with the webdriver server enabled and use the [execute script](https://w3c.github.io/webdriver/#execute-script) and [execute async script](https://w3c.github.io/webdriver/#execute-async-script) methods to achieve this.
