### ISSUE TITLE
HoloLens support?

### ISSUE THREAD

**Issue by HedwigAR** [MozillaReality/servo-unity#6]
Hi,

Is there any timeline or way of knowing the priority for HoloLens support? 

Thanks!

**Comment by philip-lamb** [comment]
In light of the recent Mozilla restructuring, this timeline is ... indeterminate. Hope to be able to update this with better news in the future.

**Comment by HedwigAR** [comment]
Hi! I was afraid of that, heard the whole AR/VR parts of Mozilla were hit hardest. I came about this through the holodevelopers slack, it's organised through Microsoft for discussion about hololens but also more general AR discussion. I don't know if you'd be interested in joining, but if you are let me know I'll send you the invite link. 

Thanks for getting back to me on this!
