### ISSUE TITLE
DllNotFoundException

### ISSUE THREAD

**Issue by feather0611** [MozillaReality/servo-unity#7]
Hi! I'm very new to Unity and C#.
Thanks for made this wonderful plugin! It's a important function to my project.
But when I try to import the ExampleScene and run, it comes out with many errors.
I can't figure out how to fix it. 
<img width="918" alt="截圖 2020-09-06 上午2 02 43" src="https://user-images.githubusercontent.com/32213432/92310916-1c536c80-efe5-11ea-8ad9-65eb790b1f14.png">
I've already build the ```servo_unity.bundle```, and also copied ```libsimpleservo2``` files to Unity's installation directory.
I found most of them may caused by cs file can't find classes in different files in some reason.
I think I'm almost there. But have no idea to fix this Exception. 
My enviroment is Mac OS X 10.15.6, Unity version is 2020.1.4f1.
Can you please give me a hand?

**Comment by arsi0001** [comment]
did you fix your problem?

**Comment by SuperJumpBros** [comment]
I really hope someone can help with or fix this. I need this for an iOS version of an online game I am making!

**Comment by fajarbinus** [comment]
hope someone can help with this too, I really need this for my thesis project

**Comment by benSmith1981** [comment]
I hope someone can help with this too as I cannot get around it!?

**Comment by philip-lamb** [comment]
Windows is not yet supported. Some preliminary work has been done on Windows support, but this is not yet complete. iOS and Android are not supported (not now and not likely to be anytime soon).

Since Mozilla Research was closed by Mozilla in September 2020,  I and the rest of the Servo team are no longer with Mozilla. The Servo project is now under the stewardship of the Linux Foundation. All future work on Servo Unity will take place in my repo at https://github.com/philip-lamb/servo-unity.

**Comment by benSmith1981** [comment]
Basically Philip. I wanted to have a web browser that I can view in VR, Oculus runs on Android, so are you saying it is nor possible to use Servo on Android, and never will be? By the way this project doesn't compile under any targets...I tried to include the plugins but nothing works.

**Comment by jdm** [comment]
Servo dropped support for Android in late 2019 or early 2020. It would be possible to resurrect it, but would definitely take sustained work.

**Comment by kalucky0** [comment]
@philip-lamb When can we expect Windows support and will there be issues page available in the new repo?

**Comment by Enemy-77** [comment]
Hey guys! Did you solved this, I meet thre same problem today. Anyone can help ?
